### ISSUE TITLE
starters show up in the bullpen section sometimes

### ISSUE THREAD

**Issue by spiantino** [spiantino/baseball-stats#29]
not sure why. i think we had a heuristic for determining if a pitcher was a starter or not, but it might be that the profile has a better way to differentiate this (e.g. Position being SP RP or something)

**Comment by aleko-** [comment]
do you have the date from a game where this occurred? I think the heuristic is only applied when determining starters for the pitching leaderboard. Starting pitcher and bullpen for each game comes from the game data.

the pitcher data is found in ['preview']['liveData']['boxscore']['teams']['home']['pitchers'] (for bullpen the last array is 'bullpen' instead of 'pitchers'). when the previews are generated there should only be one name in the 'pitchers' array at that point (which is the assumed starter). if a reliever enters the game then the live data updates by moving that reliever from the 'bullpen' array to 'pitchers' array. 

when this error occurs does the report still show the correct starting pitcher? Or does it incorrectly show a reliever as the starter instead?

**Comment by spiantino** [comment]
For instance, on last nights game Noah Syndergaard shows up in the Mets bullpen section. So I think, technically, starters can be in the bullpen because they're technically available to pitch if necessary, even though they're traditionally starters.

So let's call this a wontfix since it's actually accurate but counter intuitive.

The starting pitcher table doesn't seem to have any issues
